# Product entity menu items (entity 4.1). Cela définit un lien de menu sous le Structurelien pour la liste de produits (la page construite avec notre gestionnaire de création de liste).
entity.product.collection:
  title: 'Product list'
  route_name: entity.product.collection
  description: 'List Product entities'
  parent: system.admin_structure
  weight: 100

# Importer entity menu items (entity de configuration 5.1)
entity.importer.collection:
  title: 'Importer list'
  route_name: entity.importer.collection
  description: 'List Importer entities'
  parent: system.admin_structure
  weight: 99
