# 3Vous vous en souvenez du chapitre 5 , Liens de menus et de menus , n'est-ce pas? La route de base est toujours la route canonique de l'entité,
#  qui regroupe essentiellement les ongletsensemble. Ensuite, les itinéraires que nous utilisons pour les deux autres tâches
#  sont les liens edit_formet delete_formdu type d'entité. Vous pouvez vous référer à la section des liens de l'annotation du plugin de type Entité pour comprendre
#  d'où ils viennent. La raison pour laquelle nous ne devons préciser les paramètres ici (car ces routes exigent un ID de produit) est parce que la ligne de base a ce paramètre dans l'URL  déjà .
#  Ainsi, les tâches utiliseront celle-ci . A nd ce qui est très pratique.

# Product entity task items
entity.product.canonical:
  route_name: entity.product.canonical
  base_route: entity.product.canonical
  title: 'View'

entity.product.edit_form:
  route_name: entity.product.edit_form
  base_route: entity.product.canonical
  title: 'Edit'

entity.product.delete_form:
  route_name: entity.product.delete_form
  base_route: entity.product.canonical
  title: Delete
  weight: 10
